Refactor the toolkit to use the new Python_Toolkit
BHoM/Numpy_Toolkit pull request #12
Opened 2020-01-31 15:33 UTC by epignatelli

### NOTE: Depends on 
https://github.com/BHoM/Python_Toolkit/pull/2
It will compile if you're not on that branch, but the toolkit will not work.

### Issues addressed by this PR

Closes #1 

### Test files

The test is done by just compiling the application and checking the `AppData/Roaming/BHoM` directory contains a `python-3.7.3-embed-amd64` folder. Then, it can be tested in tandem with this pr https://github.com/BHoM/Keras_Toolkit/pull/14. `LoadImg` is a simple function to test.

### Changelog

- Centralise the python local installation to `AppData/Roaming/BHoM`
- Add PostBuild events to install python at compile time
- Add the possibility to install modules from post build events

### Additional comments

@FraserGreenroyd this pr does not have labels because they are not set for this repo. 
I will raise an issue for that, would it be ok to pick it up?
@MarthaVoul I added you to this pull request just to start familiarising with what is happening on the framework side. I do not expect you to pick up the review, but you can if you want. So, no pressure :)

2020-01-31 15:39 UTC, epignatelli commented
CTRL C + CTRL V
@alelom @FraserGreenroyd all ready for review! Let me know if you need help with that!

2020-02-03 09:30 UTC, FraserGreenroyd requested changes
I could not get this to work in the way described in the PR body, I could not get Python installer using the dependent toolkits, nor test Numpy_Engine itself I'm afraid. See some comments on the code - might be worth going through this together at some point @epignatelli ?

2020-02-03 09:30 UTC, FraserGreenroyd commented on Numpy_Engine/Convert/ToNumpy.cs
> + * Copyright (c) 2015 - 2019, the respective contributors. All rights reserved.
Copyright now needs to be 2020

2020-02-03 09:30 UTC, FraserGreenroyd commented on Numpy_Engine/Numpy_Engine.csproj
> +      <HintPath>..\..\Python_Toolkit\Build\Python_Engine.dll</HintPath>
Copy local should be set to false

2020-02-03 09:30 UTC, FraserGreenroyd commented on Numpy_Engine/Numpy_Engine.csproj
> +$(SolutionDir)/../Python_Toolkit/Python_PostBuild/bin/Debug/Python_Postbuild.exe "numpy"</PostBuildEvent>
This wasn't working for me - but if I removed `Installing keras in python at compile time` then it did. With that in, it had a 9009 error, but removing that would make it build (but Python did not install - more on that in Python_Toolkit).

2020-02-03 09:30 UTC, FraserGreenroyd commented on src/Numpy/Numpy.csproj
> +      <HintPath>..\..\..\Python_Toolkit\Build\Python_Engine.dll</HintPath>
This wasn't working for me - but if I removed `Installing keras in python at compile time` then it did. With that in, it had a 9009 error, but removing that would make it build (but Python did not install - more on that in Python_Toolkit).

2020-02-13 11:45 UTC, FraserGreenroyd approved these changes
Have re run the steps in the PR body and am happy this is now working following the changes @epignatelli

2020-02-13 11:50 UTC, epignatelli commented
Thanks @FraserGreenroyd!

@alelom since this will be pretty foundational, would you mind trying this as well?

2020-02-14 08:19 UTC, epignatelli commented
@alelom , on a second thought, I am merging for the moment. Could you still test this anyway, and raise an issue in case it doesn't work? I am aiming for a wider testing audience.

2020-02-14 08:19 UTC, merged

2020-02-14 10:55 UTC, alelom commented
> @alelom , on a second thought, I am merging for the moment. Could you still test this anyway, and raise an issue in case it doesn't work? I am aiming for a wider testing audience.

Works fine. See also my comment https://github.com/BHoM/Keras_Toolkit/pull/14#issuecomment-586209512